### ISSUE TITLE
update to remove deprecated api's etc.

### ISSUE THREAD

**Issue by underscorediscovery** [underscorediscovery/realtime-multiplayer-in-html5#9]

**Comment by BloodJohn** [comment]
in node.js 7.4.0 :

node app.js
/node/realtime-multiplayer-in-html5/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/node/realtime-multiplayer-in-html5/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node/realtime-multiplayer-in-html5/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

but it's working in 6.9.3 node.js

**Comment by BloodJohn** [comment]
(node:4416) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
